on: pull_request
name: on pull request
jobs:
  pull_request_chk:
    name: pull request checker
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14.6'
      - run: go test ./...